# Site settings
title: Christopher Ashby
description: 'Global Security Leader | Board Member | Strategic Transformation Executive'
url: 'https://ashbyca.com'
baseurl: '/'
#google_analytics: 'UA-114021955-1'
disqus_shortname: 'ashbyca'

author:
  name: 'Christopher Ashby'
  #email: ashbyc@mac.com
  #twitter_username: 
  #facebook_username:
  github_username: ashbyca
  #gist_username: ashbyca
  gist_username: YR2025%20Ashby,%20Christopher.pdf
  linkedin_username: ashbyca
  #steam_username: ashbyca
  #yelp_username: ashbyca
  reddit_username: ashbyca
  youtube_username: ashbyca
  #psn_username: kernalpanic
  #toolkit_username: projects

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
